### ISSUE TITLE
mdaines/viz.js has been archived

### ISSUE THREAD

**Issue by GrahamHannington** [magjac/d3-graphviz#107]
When I view [mdaines/viz.js](https://github.com/mdaines/viz.js/), I see the following banner message at the top of the page:

> This repository has been archived by the owner. It is now read-only.

Whoa. When did that happen?

What does this mean for d3-graphviz? Is there a successor to Viz.js? That is, is there another Viz.js-like project that will pick up any future changes to Graphviz?

**Comment by GrahamHannington** [comment]
Graphviz is the best solution that I know of for rendering graphs with subgraphs (clusters). If anyone knows of a better solution—including commercial software—please speak up!

d3-graphviz, via Viz.js, brings that proven Graphviz code to D3 and adds animation (tweening), enabling real-time (or time-lapse) visualization of data as animated block diagrams with nested structures. Sweet!

The archiving of Viz.js doesn't signal the immediate death of d3-graphviz, but it's a worrying sign for the future.

**Comment by magjac** [comment]
I don't know why viz.js is archived or even if it is deliberate or not. I've made a fork of it in the event I will need to build it in the future.

I think I've found an email to the author and just emailed him a question. If anybody else knows anything about this, please report here.

**Comment by magjac** [comment]
Reply from the author: "I've archived the project as I don't have time to maintain it. You are welcome to fork it if you like.".

**Comment by magjac** [comment]
An alternative might be https://github.com/hpcc-systems/hpcc-js-wasm. See also https://observablehq.com/@gordonsmith/graphviz-wasm-example
