### ISSUE TITLE
Shadow on nodes

### ISSUE THREAD

**Issue by lmbringas** [magjac/d3-graphviz#110]
Hey,thanks for this wrapper. It'll be nice if would be an option to active shadow on nodes. You could easy add this feature just using css.

`.node {
    filter: drop-shadow( 3px 3px 2px rgba(0, 0, 0, .2));
}
`
This is how it looks without shadow.
![imagen](https://user-images.githubusercontent.com/8726537/59546354-1f56ce80-8f02-11e9-9391-cf08ea54b72f.png)

And with shadow.
![imagen](https://user-images.githubusercontent.com/8726537/59546358-3dbcca00-8f02-11e9-881e-dce36aa87f78.png)

Regards.

**Comment by magjac** [comment]
Thank you for using the library and for the enhancement proposal.

What benefit do you see by building this into the library?

You can easily achieve this yourself with e.g.:
```
d3.select("#graph").graphviz()
  .renderDot(
    `digraph  {
       node [style="filled"]
       a [fillcolor="#d62728"]
       b [fillcolor="#1f77b4"]
       a -> b
     }`,
    () => {
      d3.selectAll('.node').style('filter','drop-shadow( 3px 3px 2px rgba(0, 0, 0, .2))');
    }
  );
```

which renders:

![image](https://user-images.githubusercontent.com/6350376/59550832-303e2900-8f70-11e9-9b49-424845851ecd.png)

**Comment by lmbringas** [comment]
Humm.. you're alright! but you could add this hack `d3.selectAll('.node').style('filter','drop-shadow( 3px 3px 2px rgba(0, 0, 0, .2))');`
So anyone else who wants shadow on nodes don't have to spend one hour reading documentation and googling as i was hahaha.
Thanks!

**Comment by magjac** [comment]
Good idea. I'll do that even though I don't consider it a hack. It the standard D3 way of doing it. I'm leaving this issue open until I've updated the documentation.

If you are doing other operations on the generated graph, please read [this note](https://github.com/magjac/d3-graphviz#note-avoid-selectionselect).

**Comment by lvwarren** [comment]
Can this be done in Jupyter notebooks using
from graphviz import *
and issuing equivalent commands.
