### ISSUE TITLE
Click events on nodes

### ISSUE THREAD

**Issue by martinRenou** [magjac/d3-graphviz#120]
Hi there!

This library looks very interesting for our use case, but we would want `click`/`hover` events on nodes. Is it possible to easily add DOM event listeners using the D3 API on nodes specifically? Reading the README I fear that those events would be added to the entire graph.

**Comment by magjac** [comment]
Yes, that’s perfectly possible. Have a look at https://bl.ocks.org/magjac/28a70231e2c9dddb84b3b20f450a215f

**Comment by martinRenou** [comment]
Thanks a lot! I'll look into it

**Comment by magjac** [comment]
@martinRenou I've built an application based on that principle: http://magjac.com/graphviz-visual-editor/. If you're playing around with [DOT](https://www.graphviz.org/doc/info/lang.html), you might have use for it. The source code is [here](https://github.com/magjac/graphviz-visual-editor).
