### ISSUE TITLE
add option for handling mouse events

### ISSUE THREAD

**Issue by vladtepesch** [magjac/d3-graphviz#125]
currently accidentally zooming happens if one tries to scroll the page and the mouse curser hovers over the graph renderer.

It should be configurable that only after selecting the graph by click the content is scroll/zoomable. maybe even completely deactivateable

**Comment by magjac** [comment]
Thanks for your suggestion, but there is already a method to do that.

You can disable zooming before you render with [*graphviz*.**zoom**(false)](https://github.com/magjac/d3-graphviz#graphviz_zoom) and enable it again when the user clicks the graph by adding a click event listener to the graph where you do [*graphviz*.**zoom**(true)](https://github.com/magjac/d3-graphviz#graphviz_zoom).
