### ISSUE TITLE
d3 graphviz does not work from offline files anymore

### ISSUE THREAD

**Issue by vladtepesch** [magjac/d3-graphviz#127]
the latest  (3.0.0) release worked from a completely local set of html+js files

With the new release it seems not to be the case anymore which is huge drawback (actually this completely disables the library from being used for offline documentation (e.g. code/project)

The reason seems to be complains about Same Origin Policies, CORS

**Comment by magjac** [comment]
Please describe what problem you get. I have no trouble using only local files. In fact, almost all the [examples](https://github.com/magjac/d3-graphviz/tree/master/examples) use only local files.

**Comment by vladtepesch** [comment]
try to create  a html in a local folder that uses local copies of the java scripts, so that no network connection is required. With the previous releases it was possible to create completely stand-alone offline documentations. 

```
<!DOCTYPE html>
<meta charset="utf-8">
<body>
<script src="d3.v5.min.js"></script>
<script src="index.min.js"></script>
<script src="d3-graphviz.min.js"></script>


<div id="graph" style="text-align: center;"></div>
<script>
d3.select("#graph").graphviz()
    .renderDot('digraph  { a -> b; }');

</script>


```


this now fails 

with :

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///c:/some/local/path//graphvizlib.wasm. (Reason: CORS request not http).

> TypeError: NetworkError when attempting to fetch resource.

**Comment by magjac** [comment]
It works if you set up a web server that serves `c:/some/local/path`, but not if you load through `file://`. It doesn't seem to be supported to load WASM files this way. See https://stackoverflow.com/questions/49636270/emscripten-generated-html-file-does-not-work-when-opened-wasm-binary-must-be-pr/49636271#49636271

It might be possible to implement a workaround à la https://stackoverflow.com/a/52732130/3122101, but I guess it must be done in Emscripten. Any comments @GordonSmith?

**Comment by vladtepesch** [comment]
> it works if you set up a web server that serves `c:/some/local/path`

Sure but you normally do not want to ship executables to enable the recipient to read provided offline docs.


> It doesn't seem to be supported to load WASM

yeah, i think hpcc explicitely mentions this at the project site:

> Cons:
>     Most browsers don't support fetch and loading pages via file:// URN, so for testing / 
>     development work you will need to run a test web server.



> It might be possible to implement a workaround [...] but I guess it must be done in Emscripten.
Without digging into it sounds like the way viz.js had chosen.

**Comment by magjac** [comment]
The d3-graphviz tests use Node.js and for that I've implemented a [polyfill for fetch](https://github.com/magjac/d3-graphviz/blob/master/test/polyfill_fetch.js). Maybe it can be adapted in some way to work in the browser.

**Comment by GordonSmith** [comment]
The offending fetch call is part of the emscripten generated stubs (which handle the loading of the wasm file at runtime).  I haven't found a practical solution other than running a local dev webserver...

**Comment by magjac** [comment]
From what I understand, it is not possible to support this other than building the WASM code into the library itself which I'm not prepared to do since it makes d3-graphviz inflexible and huge. There might however be more or less kludgy ways around this. This discussion continues in https://github.com/doxygen/doxygen/issues/7621.
