### ISSUE TITLE
table based labels are not supported anymore

### ISSUE THREAD

**Issue by vladtepesch** [magjac/d3-graphviz#128]
graphs like the following does not work anymore with the latest (3.0.0) release

```
digraph  {
  rankdir="LR";
  node [shape="plaintext"];   

 a[fontsize=9, label=<<TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" >
        
          <TR>
            <TD COLSPAN="3" BGCOLOR="azure3" >
              <b><FONT FACE="Times-Roman" POINT-SIZE="12.0" >one obj</FONT></b>
            </TD>
          </TR>
          
                <TR>
                  <TD PORT="in1" BGCOLOR="white">in1<br/>:In1</TD>
                  <TD ROWSPAN="2" BGCOLOR="azure3"> some text </TD>
                  <TD PORT="out1"  BGCOLOR="0.5 0.5 0.5">out1<br/>:Out1</TD>
                </TR>
                <TR>
                  <TD PORT="in2"   HREF="somepage.html" BGCOLOR="0.45 0.5 0.75">in2<br/>:In2</TD>
                  <TD PORT="out2"  HREF="somepage.html"   BGCOLOR="0.8 0.5 1">out2<br/>:Out2</TD>
                </TR>
          </TABLE>>];

I1 -> a:in1;
I2 -> a:in2;

a:out1 -> b;

}

```

**Comment by magjac** [comment]
Your code lacks a closing `}`. Assuming that was just a typo when writing this issue, I added it and it rendered:

![image](https://user-images.githubusercontent.com/6350376/75904206-136dbc80-5e43-11ea-90d7-036e1143dbff.png)

Clearly, this looks incorrect. Rendering using 2.x gives:

![image](https://user-images.githubusercontent.com/6350376/75904431-7d866180-5e43-11ea-94f1-82f235286b3c.png)

I assume this is a bug in Graphviz 2.42.2, but I will investigate.

**Comment by magjac** [comment]
Yes, maybe that's the reason. I've built Graphviz from source and it renders correctly both when building from HEAD and from the 2.42.2 tag.

@GordonSmith Can you comment on whether @hpcc-js/wasm was built with `libexpat` support or not.

**Comment by vladtepesch** [comment]
Maybe change to using a more recent viz.js fork and adapt to the newer API would have been the better choice

**Comment by magjac** [comment]
A fix is on the way. See https://gitter.im/d3-graphviz/community

**Comment by magjac** [comment]
It works with [@hpcc-js/wasm version 0.3.8](https://github.com/hpcc-systems/hpcc-js-wasm/blob/master/CHANGELOG.md#038-2020-03-05).

**Comment by vladtepesch** [comment]
Great 😀
