### ISSUE TITLE
3.0.3 breaks webpack bundled pages

### ISSUE THREAD

**Issue by ngg** [magjac/d3-graphviz#143]
I'm using webpack to bundle d3-graphviz together with my javascript code (graphvizlib.wasm is copied to the output directory).
I'm not using workers, and since https://github.com/magjac/d3-graphviz/commit/774f063e3ecf5c31fda000a35c6fef91728d8b38#diff-729035a455011a7aad4d195633b04a9aL14 it's not working for me. In `initViz()` both `window['@hpcc-js/wasm']` and `this._worker` are undefined for me.
If I change that condition back to the original or to `window['@hpcc-js/wasm'] || this._worker == null` it starts to work again.
If you'd like I can create a small project that reproduces this error.

**Comment by magjac** [comment]
Yes, sorry about that. It was a failed attempt to fix my own react (using webpack) application. It's fixed in v3.0.4. I also has to do this: https://github.com/magjac/graphviz-visual-editor/commit/276908dd8306d6875b750c066bb0ddf4cd6ccb66. If you have a better way to do it, please let me know.
