### ISSUE TITLE
Why tool-tip given in source the dot file is not showing as tool-tip

### ISSUE THREAD

**Issue by Soumendu003** [magjac/d3-graphviz#146]

**Comment by magjac** [comment]
It is for me. Please provide an example and I will look into it.

**Comment by Soumendu003** [comment]
I am attaching a dot file here. 

Some nodes have tooltip label. But those are not showing after rendering as SVG. 

[sample.txt](https://github.com/magjac/d3-graphviz/files/4428215/sample.txt)

**Comment by magjac** [comment]
That was a HUGE file. I cannot even render it with d3-graphviz on my machine. I'm getting "too much recursion" with Firefox 74 and "Maximum call stack size exceeded" with Chrome  80.

I'm on Ubuntu 18.04 on an i7-4600U CPU @ 2.10GHz with 12G RAM.

Here's my JavaScript code:
```
d3.select("#graph").graphviz({useWorker: true})
    .tweenPaths(false)
    .tweenShapes(false)
    .growEnteringEdges(false)
    .renderDot(`digraph {...}`);
```
What's your JavaScript code and what machine and browser are you on?

**Comment by Soumendu003** [comment]
Sorry. I found my mistake. Now it is showing.

Thank you.

Can you suggest me, how can I get the browser ready script? I need to keep
every script in my local directory.

**Comment by magjac** [comment]
I'm still curios the learn what machine you have and see (at least part of) your JavaScript code. I'm amazed that you could render it.

I'm not sure what you mean by "browser ready script", but you can always download the necessary scripts to your local directory and reference them from there.

**Comment by Soumendu003** [comment]
No, actually I didn't render the whole graph at once. It would have been
very painful to visualize as well.

My script renders only a subset of the whole graph at a time.

Thank you.
