### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by damageboy** [magjac/d3-graphviz#150]
Is there a right/wrong way of changing the fonts for a graphviz object?

When done through an attributer, the nodes seem to not take into account the selected font.
e.g.:

```
    if (datum.tag === "text") {
        selection.attr("font-family", "Consolas, \"Liberation Mono\", Courier, monospace");
        datum.attributes["font-family"] = "Consolas, \"Liberation Mono\", Courier, monospace";
    }
```

Generates nodes that their size does not correspond to the text size.

Is this a supported workflow with d3-graphviz?

**Comment by magjac** [comment]
No, you can only change individual SVG attributes with the attributer. It doesn't affect anything else since the layout has already been performed. You need us use the _Graphviz_ attribute [fontname](https://www.graphviz.org/doc/info/attrs.html#d:fontname) in your DOT source code.

**Comment by damageboy** [comment]
Thanks for that information, but will the fontname attribute in the dotfile work "all the way" in graphviz/wasm on the client side with the fonts available in the browser?

Is there some guidance on how to do so?
I'd love to add a sample to the example's folders showing up to do this...

**Comment by magjac** [comment]
If you use a fontname that's available in the browser, it will. Here's some background info that may be useful to you:

https://github.com/mdaines/viz.js/wiki/Caveats#fonts
https://github.com/mdaines/viz.js/issues/81
https://github.com/mdaines/viz.js/issues/82
