### ISSUE TITLE
"HTML-like labels" are broken since 3.0.0

### ISSUE THREAD

**Issue by gehnaphore** [magjac/d3-graphviz#153]
2.6.0 seems to work fine.

**Comment by magjac** [comment]
Please specify in what sense you think they are broken and provide an example, preferably though http://magjac.com/graphviz-visual-editor.

**Comment by gehnaphore** [comment]
They appear to work when I try them there.  But when I set things up as they are in the examples, they no longer work in 3.0.0.  Here is a jsFiddle that demonstrates the problem:

https://jsfiddle.net/daow9k63/6/

**Comment by gehnaphore** [comment]
The problem appears to be that the example was using an older version of hpcc-js/wasm (0.3.6).  When I switch to 0.3.11  (as it appears the link you sent uses) they are now working again.  So this issue is resolved, but the examples should be updated.  Thanks for the help.
