### ISSUE TITLE
Support for d3 6.0

### ISSUE THREAD

**Issue by ngg** [magjac/d3-graphviz#168]
d3 6.0 was released on 26 Aug with some breaking changes, will d3-graphviz support it?

**Comment by magjac** [comment]
Yes I have the intention of porting it, but it will not happen in the immediate future.

**Comment by magjac** [comment]
This work has now started in the [four branch](https://github.com/magjac/d3-graphviz/tree/four).

**Comment by magjac** [comment]
Resolved by https://github.com/magjac/d3-graphviz/commit/ee30f6e532e2f4435184b65b67132a67baefc4e1.
