### ISSUE TITLE
Display edge-lables

### ISSUE THREAD

**Issue by mayrmartin** [magjac/d3-graphviz#172]
Pretty new to this library so I'm sure I'm overseeing something.
I have a Digraph with edge labels like this generated by the python pydot library

```
digraph  {
    A [color=red, fillcolor=red];
    B;
    C;
    A -> B [weight=2,time=3]
    B -> C [weight=2,time=3]
}

```
When I try to render the dot file with your library, none of the edge labels are shown. Is there a possibility, to somehow access the labels or to display at least one of the labels?

**Comment by magjac** [comment]
Edge labels must be specified with the [`label`](http://graphviz.org/doc/info/attrs.html#d:label) attribute like so:
```
digraph  {
    A [color=red, fillcolor=red];
    B;
    C;
    A -> B [label="weight=2,time=3"]
    B -> C [label="weight=2,time=3"]
}
```
Try it yourself in the [Graphviz Visual Editor](http://magjac.com/graphviz-visual-editor/?dot=digraph%20%20%7B%0A%20%20%20%20A%20%5Bcolor%3Dred%2C%20fillcolor%3Dred%5D%3B%0A%20%20%20%20B%3B%0A%20%20%20%20C%3B%0A%20%20%20%20A%20-%3E%20B%20%5Blabel%3D%22weight%3D2%2Ctime%3D3%22%5D%0A%20%20%20%20B%20-%3E%20C%20%5Blabel%3D%22weight%3D2%2Ctime%3D3%22%5D%0A%7D%0A).

If you have further questions about the [DOT language](https://graphviz.org/doc/info/lang.html), I recommend you to sign up to the [Graphviz forum](https://forum.graphviz.org/c/help/5).
