### ISSUE TITLE
Not working in React?

### ISSUE THREAD

**Issue by lexax666** [magjac/d3-graphviz#174]
I can't get this to working in React. What am I doing wrong? My sample code:
https://codesandbox.io/s/romantic-feather-exf32?file=/src/Dot.js

**Comment by magjac** [comment]
It looks as if it's working to me. What is the problem?

**Comment by lexax666** [comment]
Hi @magjac I got it working after lowering its version. The newest version still doesn't work for me. Can you check it out again. Thanks in advance!

**Comment by magjac** [comment]
I think you need to copy or link the `graphvizlib.wasm` file from https://www.npmjs.com/package/@hpcc-js/wasm to the public folder.

You may want to have a look at how I do it in https://github.com/magjac/graphviz-visual-editor. Take a look at these commits:
* https://github.com/magjac/graphviz-visual-editor/commit/04dfdb165708e7aecdfc8de8e80665f36f3c4c00.
* https://github.com/magjac/graphviz-visual-editor/commit/781da3d4697e74fba3a0fe1ad27ee7ef009d9c8d

Perhaps this issue also can help you: https://github.com/magjac/d3-graphviz/issues/152.
