### ISSUE TITLE
The slack group seems dead

### ISSUE THREAD

**Issue by Luttik** [magjac/d3-graphviz#175]
Hi,

The readme currently defers users with general questions to slack. However, It seems like slack is no longer in use... I send a message a weak ago and didn't get a response, and the last message before that is from over a month ago.

If slack is deprecated as a channel it should be removed from the readme.

Kind regards,
Daan

**Comment by magjac** [comment]
I apologize for this. I totally missed that. I've answered your question now and updated the README to point to the [Graphviz forum](https://forum.graphviz.org/c/d3-graphviz/9) instead. I will probably close the d3-graphviz Slack soon. It never attracted a critical mass of users to be useful.

Thanks.

**Comment by Luttik** [comment]
Hé @magjac, Thanks for the response, both here as on slack. Since you've updated the readme I guess this issue is closed.
