### ISSUE TITLE
Event 9 RenderEnd not triggering (based on context)

### ISSUE THREAD

**Issue by Luttik** [magjac/d3-graphviz#178]
Hi, Id like to build a bridge between the python graphviz library and your (interactive) frontend graphviz library. This would enable building interactive graphviz components for data science scenarios [github repo](https://github.com/Luttik/graphviz-interactive).

However, I found that when running the code from your [more colorful demo](https://bl.ocks.org/magjac/4acffdb3afbc4f71b448a210b5060bca) in the jupyter lab it only shows the first graphviz graph. For some reason Event 8 (renderStart) is started but Event 9 (renderEnd) never occurs (after the first render call).  

[This video (for me google drive isn't displaying it well, but it works after downloading)](https://drive.google.com/file/d/1Hy43BvZvzGNssFmDYlmnjxGBkB4txi3o/view?usp=sharing) shows current behavior incl. the fact that your demo script is fully loaded into the page's dom, that the 2nd graph render is called and that it gets stuck at renderStart.

**Comment by magjac** [comment]
Thanks for the report. I would like to be able to reproduce the problem locally, but I haven't used Jupyter before. Can you instruct me?

**Comment by Luttik** [comment]
Hé Magjac,

Of course, I'd love to help you with this...
There are two flavors of jupyter that are very prevalent [jupyter notebook](https://github.com/jupyter/notebook) and [jupyter lab](https://github.com/jupyterlab/jupyterlab) for both I'd suggest [installing python 3.8 or above](https://www.python.org/downloads/).  Then you can run `pip3 install jupyterlab` (or `pip install jupyterlab` if your a windows user like me), since `jupyterlab` depends on `jupyter` which contains the `jupyter notebook` you'll have both. 

Now you can choose between running `jupyter notebook` or `jupyter lab` and a webview will open where you can go to work. Jupyter is meant for python, but in a visual way, one of the great things is that it interprets HTML. So an example codeblock would be:
```
from IPython.display import HTML
HTML('''
<script>
<!-- Your javascript goes here -->
</script>
''')
```

After encountering and posting this issue I've done more research and `jupyter notebook` seems to do strange stuff with global variables, therefore they ship with (and require you to use) [requirejs](https://requirejs.org/). Jupyter Lab doesn't require you to use `requirejs` and that is the environment where I did my testing...

It can be a bit annoying to inspect the dom that is shown in the output (below the input cells), but I don't know a way around it. One thing that is important to know is that the output of cells (and the `script` tags that are in them) are saved, so simply refreshing the page will result in automatic reloading of the output that you had before. Instead, you should use "Kernel" -> "Restart & Clear output" and refresh the page afterward to fully flush all js context. 

Now that I know that Jupyter Notebook uses requires I wonder if it would be possible to get a code example like [this one](https://bl.ocks.org/magjac/4acffdb3afbc4f71b448a210b5060bca) that only uses require rather than global imports (I know too little about this to know how that should work though). It might be that such an approach would solve it for both Jupiter environments.

**Comment by Luttik** [comment]
@magjac Maybe it should be a separate issue, but in line with my previous comment, I've started trying to solve it using RequireJs.

I've written [this gist](https://gist.github.com/Luttik/243860368b4c41808627917d3213fd12.js) to modify your example to use RequireJs. It is still broken though, regretfully, I am not entirely sure why it goes wrong. I hope you could take a look to get this thing fixed.

**Comment by magjac** [comment]
I think I need more detailed instructions. I've started **jupyter-lab** and pasted the code below into a cell, but when I click the play button ("Run the selected cells and advance"), the only thing that happens is that a new cell is created. Nothing else is displayed. I'm on Ubuntu 20.04.1 LTS and have Python 3.8.5.
```
from IPython.display import HTML
HTML('''
<!DOCTYPE html>
<meta charset="utf-8">
<body>
<script src="//d3js.org/d3.v5.min.js"></script>
<script src="https://unpkg.com/@hpcc-js/wasm@0.3.11/dist/index.min.js"></script>
<script src="https://unpkg.com/d3-graphviz@3.0.5/build/d3-graphviz.js"></script>
<div id="graph" style="text-align: center;"></div>
<script>

var dotIndex = 0;
var graphviz = d3.select("#graph").graphviz()
    .transition(function () {
        return d3.transition("main")
            .ease(d3.easeLinear)
            .delay(500)
            .duration(1500);
    })
    .logEvents(true)
    .on("initEnd", render);

function render() {
    var dotLines = dots[dotIndex];
    var dot = dotLines.join('');
    graphviz
        .renderDot(dot)
        .on("end", function () {
            dotIndex = (dotIndex + 1) % dots.length;
            render();
        });
}

var dots = [
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728"]',
        '    b [fillcolor="#1f77b4"]',
        '    a -> b',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728"]',
        '    c [fillcolor="#2ca02c"]',
        '    b [fillcolor="#1f77b4"]',
        '    a -> b',
        '    a -> c',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728"]',
        '    b [fillcolor="#1f77b4"]',
        '    c [fillcolor="#2ca02c"]',
        '    a -> b',
        '    a -> c',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728", shape="box"]',
        '    b [fillcolor="#1f77b4", shape="parallelogram"]',
        '    c [fillcolor="#2ca02c", shape="pentagon"]',
        '    a -> b',
        '    a -> c',
        '    b -> c',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="yellow", shape="star"]',
        '    b [fillcolor="yellow", shape="star"]',
        '    c [fillcolor="yellow", shape="star"]',
        '    a -> b',
        '    a -> c',
        '    b -> c',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728", shape="triangle"]',
        '    b [fillcolor="#1f77b4", shape="diamond"]',
        '    c [fillcolor="#2ca02c", shape="trapezium"]',
        '    a -> b',
        '    a -> c',
        '    b -> c',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728", shape="box"]',
        '    b [fillcolor="#1f77b4", shape="parallelogram"]',
        '    c [fillcolor="#2ca02c", shape="pentagon"]',
        '    a -> b',
        '    a -> c',
        '    b -> c',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    a [fillcolor="#d62728"]',
        '    b [fillcolor="#1f77b4"]',
        '    c [fillcolor="#2ca02c"]',
        '    a -> b',
        '    a -> c',
        '    c -> b',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    b [fillcolor="#1f77b4"]',
        '    c [fillcolor="#2ca02c"]',
        '    c -> b',
        '}'
    ],
    [
        'digraph  {',
        '    node [style="filled"]',
        '    b [fillcolor="#1f77b4"]',
        '}'
    ],
];

</script>
''')
```

**Comment by Luttik** [comment]
Ill have a look after breakfast and re add the slack lets discuss the general setup there (then people searching for the solution later dont have to scroll too much 😉). I could also do a vid call later today since we are in a similar timezone, but lets dm about that

**Comment by Luttik** [comment]
Honestly, I've been looking through the git history and still cannot reproduce the success I've had before...

Since my initial failure, I've been trying to rewrite your example using [RequireJS](https://requirejs.org/). [Here's the previous example failing Gist again](https://gist.github.com/Luttik/243860368b4c41808627917d3213fd12). I've been looking a bit more into your code and the way you build (rollup with `format: 'umd'`) should be compatible with [equirejs without shims or other weird stuff (but I'm definitely, and clearly, not an expert in rollup or requirejs). 

I have changed the Gist a bit [see v2 here](https://gist.github.com/Luttik/3c89a55d59d642732bce383bc60567f1) and it is still not working but I think I'm getting closer, but it's honestly hard to tell.

Honestly, I'm not even lear if I'm importing your code or the wasm code incorrectly.

**Comment by magjac** [comment]
This does not seem to be an issue with d3-graphviz itself. Please re-open if I'm mistaken.
