### ISSUE TITLE
can't disable zoom once enabled

### ISSUE THREAD

**Issue by lnavarette** [magjac/d3-graphviz#180]
I'm trying to create a button to toggle zoom behavior as sometimes users accidentally trigger the zoom behavior trying to scroll down the page. 

each time the button is toggled, a call is made to render the graph: 
```
        graphviz('#my-graph-id')
            .options({
                fit: true,
                width: 300,
                height: 300,
                zoom: !locked
            })
            .renderDot(props.digraph);
```

if `zoom` is initially set to `false`
 - on page load, zoom is disabled (as expected)
 - when button is pressed and zoom is toggled to `true`, zoom is enabled (as expected)
 - when button is pressed and zoom is toggled back to `false`, zoom is **still enabled**

if `zoom` is initially set to `true`
 - on page load, zoom is enabled (as expected)
 - when button is pressed and zoom is toggled to `false`, zoom is **still enabled**

tested on both `2.6.1` and `3.1.0`

**Comment by DomParfitt** [comment]
I think (not entirely sure) that this is from [https://www.github.com/magjac/d3-graphviz/tree/master/src%2Fzoom.js#L5-L14](here). 

It looks like enabling zoom creates a zoom behaviour (which presumably handles the zooming) whereas disabling zoom simply skips the creation of the zoom behaviour but doesn't delete any preexisting behaviours.

**Comment by magjac** [comment]
Although I never intended .zoom() to be used like this, I agree it makes sense and the documentation seems to imply that this is the way it should work. I'll classify it as a bug and look into a solution.

**Comment by magjac** [comment]
https://github.com/magjac/d3-graphviz/pull/183 fixes this problem. Please let me know if it works for you.

**Comment by TakhirMirza** [comment]
I have th same problem

**Comment by magjac** [comment]
@TakhirMirza Are you using the latest version?

**Comment by TakhirMirza** [comment]
I had use 3.1.0, 3.2.0 and 4.2.0. The same is working in my docker, but doesn’t work on Mac Pro 

Dr T.Mirzaev
