### ISSUE TITLE
Destroy Not Working

### ISSUE THREAD

**Issue by Archetype90** [magjac/d3-graphviz#186]
Hello,

I am attempting to destroy a graphviz object to render a new dot graph. 

I found the following test: https://github.com/magjac/d3-graphviz/blob/0a02ccd381717b5e44042a80349664b9bcdf553a/test/destroy-test.js

And have tried to implement a very simple example like above:

```
    var graphviz = d3.select("#graph").graphviz().renderDot('digraph {a -> b;}', destroy);

    function destroy() {
        graphviz.destroy();
    }
```

Trying this very simple example gives me the error:

> graphviz.destroy is not a function

I suspect I am doing something wrong, but I am not clear what with such a simple example. The graph above successfully renders, but throws the error when trying to destroy.

**Comment by magjac** [comment]
It's hard to tell whats wrong without a complete example. Perhaps you are not using the latest version?

**Comment by Archetype90** [comment]
Yup, right on. I was using version 3.0.5, which seems to not have destroy.

https://bl.ocks.org/magjac/a23d1f1405c2334f288a9cca4c0ef05b

I built my example out from that, not even considering version. Just added a callback that was meant to destroy (as above). I see why the full example is important though. Thank you for the quick response.
