### ISSUE TITLE
Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d...

### ISSUE THREAD

**Issue by broofa** [magjac/d3-graphviz#191]
Apologies for the vague bug report but I'm seeing this error and not finding a whole lot on google.  'Figured I'd at least file something here as a breadcrumb for others.

Context: I have a JS webapp that used to use the `<script source="...` style of importing `d3`, `@hpcc/wasm`, and `d3-graphviz`.  'Worked great.  Now I'm porting it over to ES modules, using `parcel` for bundling, and it's throwing the above error.

I assume this is because I'm not pulling in the @hpcc/wasm content properly, but not really sure what's going on.

Installation: `npm i parcel@nightly d3 @hpcc/wasm d3-graphviz`

Usage:
```
import * as d3 from 'd3';
import '@hpcc/wasm';
import 'd3-graphviz';

// 'Not 100% sure these are the right incantations for importing these modules,
// but it gives d3 a 'graphviz' property so... I guess it's working?

const graphviz = d3.select('#graph')
      .graphviz() //     <--  ERROR THROWN HERE?
      .renderDot(dotMarkup);
```

----

There's a few other warnings and whatnot in Chrome's console as well.  'Not sure if they're relevent...

![image](https://user-images.githubusercontent.com/164050/114215820-c7bcfa80-9901-11eb-8048-1ef689e7588b.png)

**Comment by broofa** [comment]
... I guess the main problem here is that it's unclear how to use d3-graphviz when using ESM modules and bundler, since the instructions only mention using `<script src="...`-style imports.

(Note: just saw your SO comment [here](https://stackoverflow.com/questions/49058360/react-and-d3-graphviz#comment91877259_49099080).  Not sure if that's still applicable.)

**Comment by magjac** [comment]
This kind of error is usually because a different version of @hpcc-js/wasm is used by the application and by d3-graphviz, but  I'm not sure if that is the problem you're seeing. Perhaps @GordonSmith can help?

**Comment by osequi** [comment]
I've managed to solve the problem with: `cp -Rf node_modules/@hpcc-js/wasm/dist/* public/`

NOTE: When only `graphvizlib.wasm, index.min.js` is present in `public` I'm getting the error message. When all files from `dist/` are present in `public` there is no more error message.

**Comment by broofa** [comment]
As @osequi alludes to, this seems to occur when `@hpcc-js/wasm` fails to find the "graphvizlib.wasm" file at whatever the expected location is.  In my case, this occurred because Parcel simply didn't include that file in my app bundle because it didn't detect that there was a dependency there.

Alas, the way static file dependencies are handled in Parcel makes resolving this problematic.  Briefly, you use an `import` statement to reference the file, which Parcel will resolve to whatever path it ends up copying the referenced file to.  E.g. `import wasmUrl from 'url:@hpcc-js/wasm/dist/graphvizlib.wasm'` would yield a `wasmUrl` of something like "graphviz.abc123def.wasm".

The problem is that there's no way to tell `@hpcc-js/wasm` or `d3-graphviz` about this path.   `@hpcc-js/wasm` has a global `wasmFolder` option you can set, but no option for specific files.

I eventually worked around this by loading the binary file manually and passing that directly to `@hpcc-js/wasm` via the `wasmBinary` option.
(See the use of `wasmUrl` and `wasmData` [here](https://github.com/npmgraph/npmgraph/blob/main/js/Graph.js#L11-L15) and [here](https://github.com/npmgraph/npmgraph/blob/main/js/Graph.js#L312-L317).)

Unfortunately I didn't see a way to pass the `wasmBinary` option into d3-graphviz, so I ended up dropping our use of it.

**Comment by GordonSmith** [comment]
FWIW - the way I think of graphvizlib.wasm dependency is the same as any non JS resource (like an image, video or audio file) and that it needs to get copied to the public / dist folder as part of your bundle process.  (If it ends up in the same folder as the bundled JS code then it should "just work").
If you do want to locate it in a different location then there are methods available to specify those.
It is important that matching versions of the JS and WASM files are maintained (which as pointed out was the cause of your error above).

**Comment by magjac** [comment]
Thanks all for sharing. The little I know about this, I've learnt through @hpcc-js/wasm and Gordon so I have nothing to add other than that I've solved something similar with symbolic links in the [d3-graphviz tests](https://github.com/magjac/d3-graphviz/tree/master/test/%40hpcc-js/wasm/dist) and in the [graphviz-visual-editor](https://github.com/magjac/graphviz-visual-editor/blob/master/%40hpcc-js).

If you have any suggestion for how to improve d3-graphviz in this respect, please file an enhancement issue about it and I will happily implement it. Or submit a PR if you know how to do it.
