### ISSUE TITLE
Animate cases over time

### ISSUE THREAD

**Issue by merlijnbuit** [magjac/d3-graphviz#192]
Hi,

I am curious if it is possible to animate cases over time through the graph?
This animation is from a Process Mining tool.
![17e97e4eeb9979fd94cbaa45633d9213](https://user-images.githubusercontent.com/16118919/114840156-ce9eae00-9dd6-11eb-886e-97468383efbb.gif)

**Comment by magjac** [comment]
I'm not sure I understand exactly what you're asking about, but I think that it should be possible. To say more, I would need to know more about your input data.

**Comment by merlijnbuit** [comment]
The idea is that cases are going through the process over time. At some point the difference in seconds between step A and step B is large and cases would pile up. 

What would be a good starting point to look at? 

The other tool describes it as follows:
![Screenshot 2021-04-15 at 11 47 27](https://user-images.githubusercontent.com/16118919/114849759-5c32cb80-9de0-11eb-832f-09ea77240e98.png)

**Comment by magjac** [comment]
If what you want is a static graph with just the dot moving along the edges I would suggest:
1. Render the graph once with d3-graphviz
2. Use D3 to add and animate the dots along the edges. To say more, I would need to know more about your input data.

That said, for *static* graphs, the only benefit that d3-grapvhiz offers compared to e.g. https://www.npmjs.com/package/@hpcc-js/wasm is zooming, so if you don't need that, d3-graphviz has nothing extra to offer you.
