### ISSUE TITLE
Include the pos attribute in the node attributes list [Feature Request]

### ISSUE THREAD

**Issue by umdstu** [magjac/d3-graphviz#193]
When using engines `neato` and `fdp`, which support the `pos` attribute, the position attributes aren't currently part of the objects list of attributes.

This came about by wanting to automate getting/setting the positions of an existing graph with no positions. Eg. First render the graph with the default engine, and after rendering, iterate over all of the nodes, grab it's position in the x,y coordinate system, translate or scale it to the graphviz  coordinate system, and store it back in the dot source lines of the input. Once that was done, I could then re-render the graph with either `neato` or `fdp`, and have it essentially look the same, only now I would be able to support something like moving a node to a new position in the same coordinate system.

Thanks!

**Comment by magjac** [comment]
> the position attributes aren't currently part of the objects list of attributes.

I'm not sure I understand what you are referring to here. Which object do you mean? d3-graphviz does not maintain any node object, nor a list of its attributes.

I do understand what your overall goal is, but not what you are requesting from d3-graphviz to support it.
