### ISSUE TITLE
random node not displaying 

### ISSUE THREAD

**Issue by gzzluis07** [magjac/d3-graphviz#199]
I am having issues when re-rendering a graph, seems like random node's shape and color is not rendered. When I plot the graph using http://webgraphviz.com/ it renders correctly.  Problem is similar to #197  except I am not using python dashboard.

**Comment by magjac** [comment]
What do you mean by random? Can you share an example showing the problem?

**Comment by gzzluis07** [comment]
So when I re-render my graphs sometimes  a random node in the tree will disappear only display text not shape and color.

The dot source is correct because I test it using http://webgraphviz.com/.

**Comment by gzzluis07** [comment]
> What do you mean by random? Can you share an example showing the problem?

So when I re-render my graphs sometimes a random node in the tree will disappear only display text not shape or color.

The dot source is correct because I test it using http://webgraphviz.com/.
![missing_node](https://user-images.githubusercontent.com/42304942/125692550-73198e90-56dc-411e-aa45-7ac94086274b.png)

**Comment by magjac** [comment]
I need an example that reproduces the problem in order to be able to help.

**Comment by magjac** [comment]
Closing due to lack of response.
