### ISSUE TITLE
HTML Strings not rendering correctly

### ISSUE THREAD

**Issue by ByronLudwig** [magjac/d3-graphviz#200]
Given Dot: digraph "Test" { "One" -> "Two" [label=&lt;&lt;B&gt;Label&lt;/B&gt;&gt;] "One" "Two" }

Expected Output (Which renders fine using online renderer):
![image](https://user-images.githubusercontent.com/14773418/127508171-2859ef95-64e7-43c9-a479-1a0571767583.png)

Actual Output:
![image](https://user-images.githubusercontent.com/14773418/127508228-24612166-32ad-419b-8c7c-e87324de3801.png)

**Comment by magjac** [comment]
I would need a complete example to investigate this further. This example works without any problems for me:
```
<!DOCTYPE html>
<meta charset="utf-8">
<body>
<script src="../node_modules/d3/dist/d3.js"></script>
<script src="../node_modules/@hpcc-js/wasm/dist/index.min.js"></script>
<script src="../build/d3-graphviz.js"></script>
<div id="graph" style="text-align: center;"></div>
<script>

d3.select("#graph").graphviz()
    .renderDot('digraph "Test" { "One" -> "Two" [label=<<B>Label</B>>] "One" "Two" }');

</script>
```

**Comment by ByronLudwig** [comment]
I have these 2 libs:
<script src="https://unpkg.com/@hpcc-js/wasm@0.3.6/dist/index.min.js"></script>
<script src="https://unpkg.com/d3-graphviz@3.0.0/build/d3-graphviz.js"></script>

If I remove the version on the hpcc-js then it seems to work.
I think maybe there is a compatability issue?

If I need to update the libs that should be okay then, it seems resolved

**Comment by magjac** [comment]
Thanks for the feedback. Yes, unfortunately the @hpcc-js/wasm version must match the version d3-graphviz was built with. You can see the matching versions in the [CHANGELOG](https://github.com/magjac/d3-graphviz/blob/master/CHANGELOG.md).

@GordonSmith I guess there's still is no way to avoid this version dependency. Or is it?

**Comment by GordonSmith** [comment]
@magjac - you could:
1.  Move your dependency on @hpcc-js/wasm to a "devDependency"
2.  Bundle @hpcc-js/wasm JS into your dist JS
3.  Copy the wasm file into your dist folder and include in your package

This is what I do for my @hpcc-js/graph package.

**Comment by magjac** [comment]
Thanks Gordon. I may do that, but it doesn't really feel good to bundle such a huge dependency. Do you know *why* the versions much match? Is it deliberate or just a the way WASM works?

**Comment by GordonSmith** [comment]
The process consists of two parts, the raw wasm file and the JS loader.  The JS loader maps all the JS methods to the raw methods in the WASM along with the parameter lists and return values, so when they get out of sync bad things will happen...

Given you have a tight dependency on the wasm code I wouldn't get too hung up on the size issue (FWIW it did get smaller in my latest release).

**Comment by magjac** [comment]
Thanks Gordon.
