### ISSUE TITLE
Create a Node with parent-node or children-node

### ISSUE THREAD

**Issue by Heidernlee** [magjac/d3-graphviz#206]
Hi, Thanks for providing such a good tool for creating workflow with JavaScript.

How can I create a Node with parent or children node ?
maybe subgraph statement ? I cannot find any example for this case. 
like the following workflow :  

![HeidernleeExample](https://user-images.githubusercontent.com/25810034/142978117-35df668e-cb84-43ce-9c0b-13eae13e1dd3.png)

**Comment by magjac** [comment]
You'll probably get better answers from the experts at https://forum.graphviz.org/c/help/5, but I think what you're looking for is clusters. See https://graphviz.org/Gallery/directed/cluster.html.

**Comment by Heidernlee** [comment]
Thanks for your response .
This example [Undirected Graph Clusters] from
https://graphviz.org/Gallery/undirected/fdpclust.html

is exactly what I was looking for.
I've tried almost 10 kinds of D3 based library , 
graphviz is the only one which can solved this issue.

Thanks again .

**Comment by magjac** [comment]
Thanks for the feedback and the kind words. I'm glad I could be of help. I'm closing this issue now.
