### ISSUE TITLE
transition weird behavior

### ISSUE THREAD

**Issue by kasra0** [magjac/d3-graphviz#209]
Hi,

I have this code : 

```
import * as d3             from 'd3'
import {graphviz}          from "d3-graphviz"

function demo2(selector){   

    const graph  =  graphviz(selector);             // OK : but transition is not working
    //const graph = d3.select(selector).graphviz()// KO : d3__WEBPACK_IMPORTED_MODULE_0__.select(...).graphviz is not a function
    const g1         =  `digraph  {a -> b}`;
    const g2         =  `digraph  {a -> b -> c}`;
    const dots       =  [g1,g2]
    const next       =  (index)=>(index + 1) % dots.length
    const render     =  (index)=> graph.renderDot(dots[index]).on("end", render.bind(null,next(index)));
    const transition =  ()=> d3.transition("demo2").ease(d3.easeLinear).delay(500).duration(2000);
    graph.transition(transition).on("initEnd", render.bind(null,0));
    //.logEvents(true).
}
```

The video link shows the weird result.
Is that a bug or the code is wrong ?

Thanks .

https://user-images.githubusercontent.com/16036382/147910840-e20369b2-9f7d-40e9-aa18-0e9cc6edde3c.mp4

**Comment by magjac** [comment]
I can't say since it's not a complete example that I can run.

I made an example based on your code and it behaves as I expect:

```
<!DOCTYPE html>
<meta charset="utf-8">
<body>
<script src="../node_modules/d3/dist/d3.js"></script>
<script src="../node_modules/@hpcc-js/wasm/dist/index.min.js"></script>
<script src="../build/d3-graphviz.js"></script>
<div id="graph" style="width: 300px; height: 300px; border: 1px solid black"></div>
<script>

function demo2(selector){   

//    const graph  =  graphviz(selector);             // OK : but transition is not working
    const graph = d3.select(selector).graphviz()// KO : d3__WEBPACK_IMPORTED_MODULE_0__.select(...).graphviz is not a function
    const g1         =  `digraph  {a -> b}`;
    const g2         =  `digraph  {a -> b -> c}`;
    const dots       =  [g1,g2]
    const next       =  (index)=>(index + 1) % dots.length
    const render     =  (index)=> graph.renderDot(dots[index]).on("end", render.bind(null,next(index)));
    const transition =  ()=> d3.transition("demo2").ease(d3.easeLinear).delay(500).duration(2000);
    graph.transition(transition).on("initEnd", render.bind(null,0));
    //.logEvents(true).
}

demo2("#graph");

</script>
```
https://youtu.be/FOGN6vkWWGQ

**Comment by kasra0** [comment]
Here is the repo:

- git clone https://bitbucket.org/kasrashahram/d3-graphviz-webpack-debug.git
- cd ./d3-graphviz-webpack-debug/
- npm install
- npm run dev-server

in dst/index.html 

you will see 

window.onload = function (){
       //demo1("#graph1")
    demo2("#graph2")
    }
you can comment/uncomment to see the differences

thanks for your help

**Comment by kasra0** [comment]
I am pretty sure that is a bundle problem with webpack 
I have to be able of using the line **d3.select(select).graphviz()**

Could you tell me which code makes that line possible?

Thanks

**Comment by kasra0** [comment]
It works now, 

https://user-images.githubusercontent.com/16036382/147956855-127fd484-0839-4fef-808a-692b93c14b3d.mp4

I updated the repo
 https://bitbucket.org/kasrashahram/d3-graphviz-webpack-debug.git

At least the demos work outside of the HTML with the use of **_d3.select(selector).graphviz()_**
with some basic webpack config.

I have never succeeded in making the transition works properly with the direct use of :
```
import {graphviz}   from "d3-graphviz"
const graph       = graphviz(selector) 
```

Hope it helps.

Thanks
