### ISSUE TITLE
Fade-In / Fade-Out new nodes in place instead of sliding in from top

### ISSUE THREAD

**Issue by otahirs** [magjac/d3-graphviz#210]
Currently new elements appear from top of the screen and slide in. (and slide out back to top once they are deleted).
I find this behavior quite disturbing, when large part of the graph is changing. 
Would it be possible to change the settings / code alteration so the newly added nodes just fade in in-place instead of sliding from top of the screen?

**Comment by magjac** [comment]
I think that this happens only when you render the first graph and is due to the SVG itself is growing from zero size. On subsequent rendering this should not happen unless you turn off fading.

Please provide a complete example if you want me to have a deeper look.

**Comment by otahirs** [comment]
Oh, I see, all of the movement is due to the main svg element is growing/shrinking in size.
thanks
