### ISSUE TITLE
How to change nodes on the base of the existing dot file?

### ISSUE THREAD

**Issue by SINC-G** [magjac/d3-graphviz#221]
Maybe change node text or add text to the node. Or go further to add a node to node.

So I test to under code after rendering complete, but nothing was selected. 
```
const s = d3.select('#graph').selectWithoutDataPropagation("svg").selectWithoutDataPropagation("g");
```

And whether I can only change the dot source file？

**Comment by magjac** [comment]
Sorry, I don't understand what your asking for.

Please provide a complete example if you want me to take a deeper look at a particular problem.

**Comment by SINC-G** [comment]
@magjac so sorry for my English. I'm too confused.

I will try again. And I'll sort out my problems.

I'm sorry to bother you.
