### ISSUE TITLE
Is there anyway to prevent the use of external resources?

### ISSUE THREAD

**Issue by Fexyler** [magjac/d3-graphviz#222]
Hey There,

I wonder that how can I prevent d3-graphviz to not use external resources like some javascript and wasm files from the CDNs. Is there anyway to use these stuff without sending a request to external IPs? Do you guys know how can I put them to my build? In the below you can see that requests I am talking about.

<img width="1235" alt="graphviz-problem" src="https://user-images.githubusercontent.com/30533238/155026345-06d16e84-a816-4da0-9fa8-a084d3b6a90b.png">

**Comment by magjac** [comment]
Have look at the examples, e.g. https://github.com/magjac/d3-graphviz/blob/master/examples/basic.html.

**Comment by Fexyler** [comment]
Okay I find out how to do it, thank you Magnus!

**Comment by magjac** [comment]
If you want to bundle it into your build there are probably many alternatives. I'm a newbie in that area, but I've bundled it myself in https://github.com/magjac/graphviz-visual-editor which is a react project, if you want to look at that.
