### ISSUE TITLE
What would it take to draw my own Nodes?

### ISSUE THREAD

**Issue by Vithanco** [magjac/d3-graphviz#226]
I only found this library recently. It looks absolutely great and as it does most things I want to do. 

But I stumbled about this comment from readme.md: 
`NOTE: User-defined shapes are not supported.`

What would it take to take over node drawing? I would like to create notes that look like this: 
![image](https://user-images.githubusercontent.com/4871984/160298261-99de6b0a-da51-43c1-ab70-8bb94862f0b5.png)

One way could be to add this style to Graphviz itself - and I might need to look into this. But what would be other possibilities? Any high level ideas? (If my question isn't too crazy). 

Many thanks in advance!

**Comment by magjac** [comment]
Sorry for the delay and thanks for your interest.

I noted that you got some answers already at https://forum.graphviz.org/t/how-to-create-a-new-node-type/1096.
