### ISSUE TITLE
Object Constancy broken when nodes are modified

### ISSUE THREAD

**Issue by rumpeltux** [magjac/d3-graphviz#227]
See demo: https://pastebin.com/TBp5BHNn

In some cases in a transition should keep/move a node, but the node fades out and an equal replacement fades in again.

Instructions to reproduce:
* click "render" to observe a normal transition
* click "highlight" to modify the dom (add stroke-with attribute to the ellipsis)
* click "render" again to observe a broken transition node 0 ("foo") fades out and the same node fades in again

Note: weirdly enough, this seems only broken when the node is modified AND the subgraph is involved, e.g. click "highlight" then "render", the first transition is still fine.

**Comment by rumpeltux** [comment]
This can be worked around by replacing `select('ellipsis')` with `selectWithoutDataPropagation('ellipsis')`

**Comment by magjac** [comment]
Yes, this is common pitfall with D3. This is detailed in the [README](https://github.com/magjac/d3-graphviz#note-avoid-selectionselect).
