### ISSUE TITLE
Add support for transitioned zoom reset

### ISSUE THREAD

**Issue by magjac** [magjac/d3-graphviz#23]
The current zoom reset functionality is instantaneous. This enhancement calls for a way for the user to specify a transition to be used during zoom reset in a way that can be supported by the [public API](https://github.com/magjac/d3-graphviz#api-reference), rather than using the internal variables of d3-graphviz as @GrahamHannington does in https://github.com/magjac/d3-graphviz/issues/21#issuecomment-348431973.

**Comment by GrahamHannington** [comment]
Thanks for this enhancement.

I've replaced my previous code (that used internal variables) with:

    graphviz.resetZoom(graphviz.transition())

This works for me.

Not your problem; and perhaps not a problem at all: when I returned from the Christmas break, I looked at my code and saw I was using `transition("smooth")`, without any memory of where I got the `"smooth"` name from. I'm not defining that named transition in my own code; perhaps I was, but later deleted it. I can't find it defined in `d3-graphviz` or `d3`. But it worked without error; as does the code above, with no transition name. Seems the default transition is, er, _smooth_. Or is there something else going on here?

**Comment by magjac** [comment]
I'm not sure what your code above actually does, but most certainly not what you think. From the [graphviz.transition()](https://github.com/magjac/d3-graphviz#graphviz_transition) documentation: 

> ...returns the graph renderer instance, not the transition

You should use `graphviz.resetZoom(d3.transition())` or `graphviz.resetZoom(graphviz.active())`.

The default transition is not "smooth", but null. From the [d3.transition()](https://github.com/d3/d3-transition#transition) documentation:

>  If a name is not specified, null is used.

Maybe you gave it an arbitrary name because of this note from the  [graphviz.transition()](https://github.com/magjac/d3-graphviz#graphviz_transition) documentation:

> NOTE: Transitions should be named if zooming is enabled. Transitions using the null name will be interrupted by the zoom behavior, causing the graph to be rendered incorrectly.

**Comment by GrahamHannington** [comment]
👍

Thanks for setting me straight.

I'm now using:

```javascript
// Define D3 transition for zoom reset
transitionSmooth = d3.transition("smooth")
  .duration(750)
  .ease(d3.easeLinear)
```

followed by:

```javascript
// Resets to original scale
exports.resetZoom = function resetZoom() {
  graphviz.resetZoom(transitionSmooth)
}
```

where `exports.resetZoom` is a public method invoked by clicking a "Reset zoom" button in the UI.
