### ISSUE TITLE
Calculate layout positions only without drawing

### ISSUE THREAD

**Issue by klaraseitz** [magjac/d3-graphviz#237]
I'd like to use my own visualization for dot files. Therefore, I am looking to only use graphviz to calculate the positions of the layout and return a dot string with positions. 

I tried using graphviz().layout but this directly returns an svg

Is there a way to only access the dot string with positions of the calculated layout?

**Comment by TheKneupner** [comment]
I don't think you want to use d3-graphviz for that case. You most likely want to use https://github.com/hpcc-systems/hpcc-js-wasm "only". 
What the wasm allows you is to layout to JSON. I can provide some more guidance after that is needed.

**Comment by magjac** [comment]
I agree with @TheKneupner.
