### ISSUE TITLE
Update to hpcc-js/wasm 1.16.0 (Graphviz 6)

### ISSUE THREAD

**Issue by mrdrogdrog** [magjac/d3-graphviz#245]
hpcc-js/wasm has been updated to graphviz 6.0.0

https://github.com/hpcc-systems/hpcc-js-wasm/releases/tag/v1.16.0

Is this still compatible?

**Comment by magjac** [comment]
Yes I think so, but we should wait for 6.0.1. See https://gitlab.com/graphviz/graphviz/-/merge_requests/2836.

**Comment by magjac** [comment]
Updated to @hpss-js/wasm 1.16.1 (Graphviz 6.0.1) in v4.4.0.
