### ISSUE TITLE
Some Examples are outdated

### ISSUE THREAD

**Issue by BruceChen2017** [magjac/d3-graphviz#246]
Since now this package is using d3@6, so some api of d3 in the examples is removed. For example, in the file `basic-add-edge.html`, `d3.event` and `d3.mouse` are both removed.

**Comment by magjac** [comment]
Your right. It seems I have forgotten to update any example when going to d3@6. Thanks.

**Comment by wagle** [comment]
I'm wondering of I could get a version of https://gist.github.com/magjac/4acffdb3afbc4f71b448a210b5060bca that uses modern versions of the three packages?  I'm hoping that starting with that as a running start would be a lot easier for me.  Hopefully someone out there already knows what needs to be done?
