### ISSUE TITLE
Distance between horizontal nodes shrinks if you specify fontname sans-serif, but with fontname Arial result is fine

### ISSUE THREAD

**Issue by reregaga** [magjac/d3-graphviz#252]
Script:
```
digraph {
    splines=false
    node [shape=box]
    
    b_start [label="Bob"]
    b_0 [label="" shape=point height=0]
    b_1 [label="" shape=point height=0]
    b_end [label="Bob"]
    b_start -> b_0 -> b_1 -> b_end [style="dashed" arrowhead="none"]
    
    a_start [label="Alice"]
    a_0 [label="" shape=point height=0]
    a_1 [label="" shape=point height=0]
    a_end [label="Alice"]
    a_start -> a_0 -> a_1 -> a_end [style="dashed" arrowhead="none"]
    
    {rank=same; b_0 -> a_0 [weight=0 arrowhead=vee fontname="Arial" label=<<B>1 </B>Authentication request>]}
    {rank=same; a_1 -> b_1 [weight=0 arrowhead=vee fontname="Arial" label=<<B>2 </B>Authentication response>]}
}
```
[Link to editor](http://magjac.com/graphviz-visual-editor/?dot=digraph%20%7B%0D%0A%20%20%20%20splines%3Dfalse%0D%0A%20%20%20%20node%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%0D%0A%20%20%20%20b_start%20%5Blabel%3D%22Bob%22%5D%0D%0A%20%20%20%20b_0%20%5Blabel%3D%22%22%20shape%3Dpoint%20height%3D0%5D%0D%0A%20%20%20%20b_1%20%5Blabel%3D%22%22%20shape%3Dpoint%20height%3D0%5D%0D%0A%20%20%20%20b_end%20%5Blabel%3D%22Bob%22%5D%0D%0A%20%20%20%20b_start%20-%3E%20b_0%20-%3E%20b_1%20-%3E%20b_end%20%5Bstyle%3D%22dashed%22%20arrowhead%3D%22none%22%5D%0D%0A%20%20%20%20%0D%0A%20%20%20%20a_start%20%5Blabel%3D%22Alice%22%5D%0D%0A%20%20%20%20a_0%20%5Blabel%3D%22%22%20shape%3Dpoint%20height%3D0%5D%0D%0A%20%20%20%20a_1%20%5Blabel%3D%22%22%20shape%3Dpoint%20height%3D0%5D%0D%0A%20%20%20%20a_end%20%5Blabel%3D%22Alice%22%5D%0D%0A%20%20%20%20a_start%20-%3E%20a_0%20-%3E%20a_1%20-%3E%20a_end%20%5Bstyle%3D%22dashed%22%20arrowhead%3D%22none%22%5D%0D%0A%20%20%20%20%0D%0A%20%20%20%20%7Brank%3Dsame%3B%20b_0%20-%3E%20a_0%20%5Bweight%3D0%20arrowhead%3Dvee%20fontname%3D%22sans-serif%22%20label%3D%3C%3CB%3E1%20%3C%2FB%3EAuthentication%20request%3E%5D%7D%0D%0A%20%20%20%20%7Brank%3Dsame%3B%20a_1%20-%3E%20b_1%20%5Bweight%3D0%20arrowhead%3Dvee%20fontname%3D%22sans-serif%22%20label%3D%3C%3CB%3E2%20%3C%2FB%3EAuthentication%20response%3E%5D%7D%0D%0A%7D)
Result:
![mj-arial](https://user-images.githubusercontent.com/76629445/195307781-696e5b73-0cbe-49b2-af90-9139af9d4345.png)

If you change fontname `Arial` to `sans-serif`, result:
![ss](https://user-images.githubusercontent.com/76629445/195307367-4de5a6e8-2320-4410-9f9c-9c121777019a.png)

If you run `dot -Tpng i.gv -o o.png`, it works as expected in both cases:
![arial](https://user-images.githubusercontent.com/76629445/195306913-20de7bdd-cb02-41a6-8aef-f36b97b4f53c.png)

**Comment by magjac** [comment]
I think this problem is due to the graph being rendered with access to certain fonts, while being view without access to the same fonts. See https://gitlab.com/graphviz/graphviz/-/issues/1891 or https://github.com/mdaines/viz.js/issues/81 for similar problems.

In any case, it's most certainly not a problem in d3-graphviz itself so I'm closing this issue now. Please feel free to reopen if you disagree.
