### ISSUE TITLE
Cannot find wasm files

### ISSUE THREAD

**Issue by piacenti** [magjac/d3-graphviz#255]
During startup I've recently (last 3 weeks) been getting the error below when script attempts to load https://unpkg.com/@hpcc-js/wasm/dist/index.min.js -> https://unpkg.com/@hpcc-js/wasm@2.2.0/dist/index.min.js

`Cannot find "/dist/index.min.js" in @hpcc-js/wasm@2.2.0`

**Comment by Vithanco** [comment]
+1

Actually, it created a "undefined caught" during dot.js initiatialisation. 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/4871984/204542325-9bd678b3-9d9b-4f23-8445-b2c52098ae5f.png">

I guess a better error message in the code would be good.

**Comment by magjac** [comment]
d3-graphviz hasn't been ported to https://github.com/hpcc-systems/hpcc-js-wasm  version 2.2 yet. See https://github.com/magjac/d3-graphviz/blob/master/CHANGELOG.md for which version to use.

**Comment by piacenti** [comment]
It may be worth updating documentation. The script tag instructions is currently using the distribution which uses version 2.2
