### ISSUE TITLE
resetZoom resets the zoom transform incorrectly after rendering a second graph

### ISSUE THREAD

**Issue by magjac** [magjac/d3-graphviz#26]
The resetZoom() method resets the zoom transform to the original transform of the *first* rendered graph, which is incorrect after a second graph has been generated on the same element. The reset needs to use the original transform from the *last* generated graph.

The problem can be seen in [this example](https://github.com/magjac/d3-graphviz/blob/master/examples/demo-zoom-fit-window.html).

**Comment by GrahamHannington** [comment]
Yes, I've just hit this problem, too.

**Comment by GrahamHannington** [comment]
Perhaps I've just had too much coffee today, but the `remove` call seemed to cause a little on-screen glitching, so I've preceded the `remove` with `display = "none"`, to "draw a veil" over the wholesale slaughter of the `<svg>` and its descendants:

    d3.select("#graph > svg").display = "none"
