### ISSUE TITLE
Git Release missing

### ISSUE THREAD

**Issue by Vithanco** [magjac/d3-graphviz#264]
Github lacks the release tag for V5.0.0.

<img width="158" alt="image" src="https://user-images.githubusercontent.com/4871984/209581669-0854d5f3-7ef6-4740-9826-340a96ae8aa6.png">

(small thing)

Good work! Thanks

**Comment by magjac** [comment]
Thanks. Fixed: https://github.com/magjac/d3-graphviz/releases/tag/v5.0.0
