### ISSUE TITLE
Can u produce a v5 sample？

### ISSUE THREAD

**Issue by cong1223** [magjac/d3-graphviz#271]
I'm going to write the following code as usual,but get the error: 
Uncaught (in promise) TypeError: (0 , d3_selection__WEBPACK_IMPORTED_MODULE_18__.select)(...).graphviz is not a function
    at initGraphviz

how can fix it? thx so much

```typescript
const graphviz = await Graphviz.load()
graphvizRef.current = (select(`#${GRAPH_ID}`) as any)
        .graphviz()
        .width('100%')
        .height('100%')
        .options({
          zoom: true,
          fit: true,
          useWorker: false
        })
```

**Comment by magjac** [comment]
I can't say if you don't provide a complete example that I can run myself.
