### ISSUE TITLE
graphvizlib.wasm missing in 5.0

### ISSUE THREAD

**Issue by papinto** [magjac/d3-graphviz#273]
After installing the newer version (5.0.2), I can't find the graphvizlib.wasm file that could be found in the @hpcc-js/wasm/dist folder in the 4.X versions.

Was this file removed on purpose? Is it no longer needed?

**Comment by magjac** [comment]
I assume you mean `test/@hpcc-js/wasm/dist/graphvizlib.wasm`. No, since 13a592a12a502e0cac54b6e22480585588a861d5 it's no longer needed.
