### ISSUE TITLE
Modify node shape from javascript

### ISSUE THREAD

**Issue by wjj1928** [magjac/d3-graphviz#276]
My dot graph file is very big, it do not define shape attribute for nodes, how can I define the default nodes shape as rectangle?

**Comment by magjac** [comment]
Questions like this are probably better suited at https://forum.graphviz.org/c/help/5, but try this:


```
digraph {
    node [shape=rectangle]
    a -> b
}
```
See the result and experiment yourself at http://magjac.com/graphviz-visual-editor/?dot=digraph%20%7B%0A%20%20%20%20node%20%5Bshape%3Drectangle%5D%0A%20%20%20%20a%20-%3E%20b%0A%7D
