### ISSUE TITLE
Have you considered writing an accompanying drag-and-drop node feature？

### ISSUE THREAD

**Issue by cong1223** [magjac/d3-graphviz#277]

**Comment by papinto** [comment]
There's an example of this on a related project by the same author: https://github.com/magjac/graphviz-visual-editor

**Comment by cong1223** [comment]
> There's an example of this on a related project by the same author: https://github.com/magjac/graphviz-visual-editor

unable to drag

**Comment by magjac** [comment]
No. I haven't.
