### ISSUE TITLE
Upgrade examples to library version 5.x

### ISSUE THREAD

**Issue by michael-emmi** [magjac/d3-graphviz#291]
The current usage examples use old versions of d3-graphviz. For example,  e.g., [d3-graphviz Basic example](https://gist.github.com/magjac/a23d1f1405c2334f288a9cca4c0ef05b) uses 3.0.5. There’s been a breaking change since then, from 4.5.x to 5.x, and I cannot seem to find a complete working example with 5.x in browser. If I simply upgrade the versions, and try to follow [this guidance](https://github.com/magjac/d3-graphviz/tree/master#defining-the-hpcc-jswasm-script-tag), I end up with “graphviz is not defined” errors.

**Comment by magjac** [comment]
Sorry for the delay. I will look into updating the on-line examples.

In the meantime, you have plenty of examples using version 5 at https://github.com/magjac/d3-graphviz/tree/master/examples.

**Comment by magjac** [comment]
It turns out that http://bl.ocks.org/ that the examples link to is no longer operation, but just redirects to https://gist.github.com/. I will have to port the examples some other JS playground.

**Comment by magjac** [comment]
The online examples have now been ported to https://blocks.roadtolarissa.com/magjac and updated to use version [5.6.0](https://github.com/magjac/d3-graphviz/blob/master/CHANGELOG.md#560--2024-08-18).
