### ISSUE TITLE
webpack4 throw cannot resolve "@hpcc-js/wasm/graphviz"

### ISSUE THREAD

**Issue by linlinyang** [magjac/d3-graphviz#298]
Webpack4 not support export fields in package.json for '@hpcc-js/wasm'.
So the use of 'import { Graphviz } from "@hpcc-js/wasm/graphviz";' will throw error.
1. In d3-graphvis/src/dot.js and d3-graphvis/src/graphviz.js:
2. Change to 'import wasm from "@hpcc-js/wasm";' .
3. And change ' Graphviz.load()' to 'wasm .Graphviz.load()' 
4. will fixed this problem.

**Comment by simongruenbacher** [comment]
Had the same problem last year. Ended up bumping the webpack version instead, but this required a more general version bump. webpack4 still seems to be pretty big, so this might happen to others as well.

**Comment by magjac** [comment]
I assume this problem is avoidable by using a later version of webpack4. Please let me know if I'm mistaken.
