### ISSUE TITLE
Tweening of shapes

### ISSUE THREAD

**Issue by andreash** [magjac/d3-graphviz#315]
I am experimenting with the SVG generated by Graphviz and was, for some reasons, deleting the <title/> elements from each node group (g, class "node"). This caused the tweening to behave awkward. Is my assumption right, that you are using the node ids in the title elements for referencing between an existing svg and the next one? If yes - could you point me to the point in the code where this is implemented? I am transferring the node id to the g element and would like to get rid of the <title> elements because auf UI design.

**Comment by magjac** [comment]
>  Is my assumption right, that you are using the node ids in the title elements for referencing between an existing svg and the next one?

By default, yes, but you can change that with the [keyMode](https://github.com/magjac/d3-graphviz?tab=readme-ov-file#graphviz_keyMode) function. For details see [Maintaining Object Constancy](https://github.com/magjac/d3-graphviz?tab=readme-ov-file#maintaining-object-constancy).

> If yes - could you point me to the point in the code where this is implemented?

It's in the [setKey function](https://github.com/magjac/d3-graphviz/blob/master/src/dot.js#L143).

**Comment by andreash** [comment]
Thanks - setting the id for nodes and edges and set keyMode to "id" works well. Deleting the <title> tags from the class="node" groups now doesn't disturb the tweening process any more. However, if I delete the <title> tag from the class="edge" svg groups as well, d3graphviz encounters an "undefined" error.

BTW, it would be great if the generated svg string is made accessible in one of the lifecylce callbacks. right now I am using a trick (I patched "parseFromString" in the DOMParser class, to get hold of the svg string bevore it is being attached to d3.

**Comment by magjac** [comment]
Happy to the hear that you got it working. You're welcome to file a separate bug report with a reproducible example for the edge problem or an enhancement request about the access to the SVG string.
