### ISSUE TITLE
Is it possible to add listener to item? 

### ISSUE THREAD

**Issue by liaodalin19903** [magjac/d3-graphviz#316]
I create a simple graphviz example as below:
```
<!DOCTYPE html>
<meta charset="utf-8">
<body>
<script src="https://unpkg.com/d3@5.16.0/dist/d3.min.js"></script>
<script src="https://unpkg.com/@hpcc-js/wasm@0.3.11/dist/index.min.js"></script>
<script src="https://unpkg.com/d3-graphviz@3.0.5/build/d3-graphviz.js"></script>
<div id="graph" style="text-align: center;"></div>
<script>

d3.select("#graph").graphviz()
    .renderDot('digraph  {a -> b -> c} ');

</script>
```
![image](https://github.com/user-attachments/assets/363f8b12-36e6-4a13-82b2-70af665c07e5)

1、whether the d3-graphviz has the ability to add listener to the node? when click it I can interact with it.

2、whether can create text on the line?

**Comment by magjac** [comment]
You don't need d3-graphviz specific functionality for that. You can use vanilla JavaScript to do it. Or you can use d3 as in the [Delete Nodes and Edge Demo Application](https://bl.ocks.org/magjac/28a70231e2c9dddb84b3b20f450a215f) that is listed under https://github.com/magjac/d3-graphviz#examples.
