### ISSUE TITLE
Use worker mode with react

### ISSUE THREAD

**Issue by andreash** [magjac/d3-graphviz#324]
Hello Magnus - from your documentation I am not sure how to activate worker mode when using d3-graphviz in React. Can you give an example how I would integrate the necessary <script ...> tags, which enable worker mode, in suche a case? I have no idea - and researched intensively - how I would integrate those tags in a function component which uses d3-graphviz. Your help is much appreciated. Best regards, Andreas

**Comment by magjac** [comment]
I'm not sure what the best way to do this is, but at least I got it working in the Graphviz Visual Editor [like this](https://github.com/magjac/graphviz-visual-editor/blob/master/src/pages/index.js#L750).
