### ISSUE TITLE
Transitions do not work in Safari

### ISSUE THREAD

**Issue by magjac** [magjac/d3-graphviz#4]
Since fixing https://github.com/magjac/d3-graphviz/issues/2, transitions no longer work in Safari.

Compare demo with [v0.1.0](http://bl.ocks.org/magjac/171fb3b845d1f5a3f905d85ca904d0a2) with [v1.0.1](https://bl.ocks.org/magjac/62665236399d049c1fdb9c24254fd548).

**Comment by magjac** [comment]
I have no means to debug this, since the only version of Safari available on Windows is 5.1.7 which does not support ES6. On Linux there is no version at all.

**Comment by coli** [comment]
This is the error in Safari

TypeError: null is not an object (evaluating 'transform.baseVal.consolidate().matrix')
getTranslation
extractElementData
extractData
dot

**Comment by magjac** [comment]
Thanks @coli. Probably the same problem as https://github.com/magjac/d3-graphviz/issues/18

**Comment by magjac** [comment]
Indeed, it was the same problem as https://github.com/magjac/d3-graphviz/issues/18.

Fixed with https://github.com/magjac/d3-graphviz/commit/e87cea2c1f15e5a207c8dbbd52f72f9638b52be4.

[Working demo with v1.3.1](https://bl.ocks.org/magjac/f485e7b915c9699aa181a11e183f8237).
